### ISSUE TITLE
Issues of Windows CI

### ISSUE THREAD

**Issue by madebr** [zeromq/czmq#1132]
In #1131, every test of `czmq_selftest` can be run separately and every subtest failure will fail the build.
I have listed the reasons of the failures here under, in the hope that they will be fixed.
- Some failures happen occasionally (Timeout)
- `zactor_test ......................***Failed`
  
  Reason: Assertion fails at end of program. Probably during unloading of czmq.dll or libzmq.dll.
  Output of manual run:
  
  ```
  PS C:\projects\build_czmq> .\Release\czmq_selftest.exe -e --test zactor_test
  Running czmq selftest 'zactor_test'...
  * zactor: OK
  Assertion failed: Successful WSASTARTUP not yet performed   (C:\projects\libzmq\src\signaler.cpp:191)
  ```
- `zdir_test ........................***Exception: SegFault`
  `czmq_selftest ....................***Exception: Other`
  fails at same point.
  A segmentation fault happens somewhere...
  
  Output (Release/x86):
  
  ```
  PS C:\projects\build_czmq> .\Release\czmq_selftest.exe -e --test zdir_test -v
  Running czmq selftest 'zdir_test'...
  * zdir:
  zdir-test-dir/initial_file
  zdir-test-dir/test_abc
  I: 15-10-22 15:23:48 zdir_watch: Command received: TIMEOUT
  I: 15-10-22 15:23:48 zdir_watch: Setting directory poll timeout to 100
  I: 15-10-22 15:23:48 zdir_watch: Successfully set directory poll timeout to 100
  I: 15-10-22 15:23:48 zdir_watch: Command received: SUBSCRIBE
  I: 15-10-22 15:23:48 zdir_watch: Subscribing to directory path: zdir-test-dir
  I: 15-10-22 15:23:48 zdir_watch: Successfully subscribed to zdir-test-dir
  I: 15-10-22 15:23:48 zdir_watch: Command received: UNSUBSCRIBE
  I: 15-10-22 15:23:48 zdir_watch: Unsubscribing from directory path: zdir-test-dir
  I: 15-10-22 15:23:48 zdir_watch: Successfully unsubscribed from zdir-test-dir
  I: 15-10-22 15:23:48 zdir_watch: Command received: SUBSCRIBE
  I: 15-10-22 15:23:48 zdir_watch: Subscribing to directory path: zdir-test-dir
  I: 15-10-22 15:23:48 zdir_watch: Successfully subscribed to zdir-test-dir
  I: 15-10-22 15:23:49 zdir_watch: Found 1 changes in zdir-test-dir:
  I: 15-10-22 15:23:49 zdir_watch:   zdir-test-dir/test_abc created
  ```
  
  or
  
  Output (Release/x64):
  
  ```
  PS C:\projects\build_czmq> release\czmq_selftest -e -v --test zdir_test
  Running czmq selftest 'zdir_test'...
  * zdir:
  zdir-test-dir/initial_file
  zdir-test-dir/test_abc
  I: 15-10-22 15:58:34 zdir_watch: Command received: TIMEOUT
  I: 15-10-22 15:58:34 zdir_watch: Setting directory poll timeout to 100
  I: 15-10-22 15:58:34 zdir_watch: Successfully set directory poll timeout to 100
  I: 15-10-22 15:58:34 zdir_watch: Command received: SUBSCRIBE
  I: 15-10-22 15:58:34 zdir_watch: Subscribing to directory path: zdir-test-dir
  I: 15-10-22 15:58:34 zdir_watch: Successfully subscribed to zdir-test-dir
  I: 15-10-22 15:58:34 zdir_watch: Command received: UNSUBSCRIBE
  I: 15-10-22 15:58:34 zdir_watch: Unsubscribing from directory path: zdir-test-dir
  I: 15-10-22 15:58:34 zdir_watch: Successfully unsubscribed from zdir-test-dir
  ```
- `XXX_test ................................***Timeout`
  Time limit was hit.
  Default time limits for a subtest is 6 seconds.
  The limit for the complete test is 20 seconds.
  The timeout is hit occasionally, I cannot always reproduce it.
  This error is probably related to WSASTARTUP.
- `zactor_test` on `x64/Debug`
  Don't know whether this is an issue?
  
  Output:
  
  ```
  PS C:\projects\build_czmq> .\debug\czmq_selftest.exe -e --test zactor_test
  Running czmq selftest 'zactor_test'...
  * zactor: OK
  E: 15-10-22 16:21:43 dangling 'PAIR' socket created at C:\projects\czmq\src\zsys.c:375
  E: 15-10-22 16:21:43 dangling sockets: cannot terminate ZMQ safely
  PS C:\projects\build_czmq> echo $?
  True
  ```

**Comment by hitstergtd** [comment]
@madebr 
Is this issue solved now. Can it be closed?

**Comment by madebr** [comment]
The issue is still existing.

See https://ci.appveyor.com/project/zeromq/czmq/build/build-481

When looking at the output of the tests, all tests failed due to a timeout.
Some tests should at least have succeeded.

There is no sign of a SEGFAULT, but I believe the timeout is masking them.
The tests do also not produce any output.

**Comment by hitstergtd** [comment]
@madebr 
Thanks. Hmm. I wonder if this happens if the same builds are replicated on a normal Windows build.

**Comment by madebr** [comment]
I've created pullreques #1408 which adds czmq_selftest.exe to the artifacts of the windows CI. (see https://ci.appveyor.com/project/zeromq/czmq/build/build-487/job/d2r91ienvxqedrdj/artifacts)
Running czmq_selftest.exe on my machine shows that the failed tests only occur on the appveyor servers.
The reason is unknown to me.

Running the zdir_test test fails, due to its dependence on the source tree.

**Comment by hitstergtd** [comment]
So the pull request has been merged, but I don't see a successful AppVeyor build.

**Comment by madebr** [comment]
The problem only shows up on the appveyor systems. Reason unknown.
