### ISSUE TITLE
Segfault on OSX

### ISSUE THREAD

**Issue by sphaero** [zeromq/czmq#2142]
```
Process 11855 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xe00)
    frame #0: 0x0000000100116d09 libczmq.4.dylib`zactor_is(self=0x0000000000000e00) at zactor.c:212:37 [opt]
   209  zactor_is (void *self)
   210  {
   211      assert (self);
-> 212      return ((zactor_t *) self)->tag == ZACTOR_TAG;
   213  }
   214  
   215  

(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xe00)
  * frame #0: 0x0000000100116d09 libczmq.4.dylib`zactor_is(self=0x0000000000000e00) at zactor.c:212:37 [opt]
    frame #1: 0x00000001001333da libczmq.4.dylib`zsock_resolve(self=0x0000000000000e00) at zsock.c:1842:9 [opt]
    frame #2: 0x0000000100132a7d libczmq.4.dylib`zpoller_new [inlined] zpoller_add(self=0x0000000100405dc0, reader=0x0000000000000e00) at zpoller.c:147:20 [opt]
    frame #3: 0x0000000100132a75 libczmq.4.dylib`zpoller_new(reader=0x0000000000000e00) at zpoller.c:103 [opt]
    frame #4: 0x0000000100003d4a a.out`main + 106
    frame #5: 0x00007fff714fdcc9 libdyld.dylib`start + 1
```
I just squeezed this backtrace out of someone's OSX 10.15.1 install. It's done with both czmq and libzmq master. I think this happens on CI now and then as well. Haven't checked yet. 

Code was:
```
// compile: gcc test-poll.c `pkg-config --cflags --libs libczmq`
#include "czmq.h"

// poll receive
int main()
{
    zsock_t* mdgramr = zsock_new_dgram ("udp://239.255.42.99:1151");
    assert (mdgramr);

    char *mdmessage, *maddr;

    zpoller_t *p = zpoller_new(mdgramr);
    void *which = zpoller_wait(p, 1000);
    assert(which == mdgramr);
    zmsg_t *mdmsg = zmsg_recv( mdgramr );
    assert (mdmsg);
    maddr = zmsg_popstr (mdmsg);
    mdmessage = zmsg_popstr (mdmsg);
    assert (streq(mdmessage, "HELLO"));
    zmsg_destroy ( &mdmsg );
    zsock_destroy (&mdgramr);
    zstr_free (&mdmessage);
    zstr_free (&maddr);
    zstr_free (&mdmessage);
}
```

**Comment by sappo** [comment]
This issue is still occurring on Travis. Could somebody with an osx system please investigate.

**Comment by sphaero** [comment]
there's an issue with the code: zpoller_new should end with NULL. 

Here's updated code:
```
// compile: gcc test-poll.c `pkg-config --cflags --libs libczmq`
#include "czmq.h"

// poll receive
int main()
{
    zsock_t* mdgramr = zsock_new_dgram ("udp://239.255.42.99:1151");
    assert (mdgramr);

    char *mdmessage, *maddr;

    zpoller_t *p = zpoller_new(mdgramr, NULL);
    void *which = zpoller_wait(p, 1000);
    assert(which == mdgramr);
    zmsg_t *mdmsg = zmsg_recv( mdgramr );
    assert (mdmsg);
    maddr = zmsg_popstr (mdmsg);
    mdmessage = zmsg_popstr (mdmsg);
    assert (streq(mdmessage, "HELLO"));
    zmsg_destroy ( &mdmsg );
    zsock_destroy (&mdgramr);
    zstr_free (&mdmessage);
    zstr_free (&maddr);
    zstr_free (&mdmessage);
}
```

**Comment by sphaero** [comment]
I only have access to a 10.12.6 install. Both codes work fine on this system.

**Comment by bluca** [comment]
Yeah it's a va_args so that's clearly a bug, it needs to be null terminated. gcc/glibc on Linux is notoriously forgiving of those mistakes, other platforms less so.

**Comment by sappo** [comment]
@bluca are you working on a bugfix?

**Comment by bluca** [comment]
sorry don't have time right now

**Comment by sappo** [comment]
Can you point me to the error then I'll have a look at it

Am Fr., 22. Jan. 2021 um 13:51 Uhr schrieb Luca Boccassi <
notifications@github.com>:

**Comment by bluca** [comment]
Ah i thought the copy/paste from above was from our tests - I don't know then, sorry

**Comment by sphaero** [comment]
It could very well be that this is triggered by not having a NULL terminating the argument. I don't know what it will do then but if zpoller gets an illegal pointer then it's logical zsock_resolve will fail horribly.

**Comment by sappo** [comment]
@sphaero yes, I think this issue is fixed

**Comment by sphaero** [comment]
Yes let's close it. We still have problems on OSX though but we need someone with a recent machine. We could also try to add backtraces to our tests? https://stackoverflow.com/questions/3899870/print-call-stack-in-c-or-c
